## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tdma-example', ['core', 'simulator', 'mobility', 'simple-wireless-tdma', 'tdma-example'])
    obj.source = 'tdma-example.cc'